name: Gradle CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8, 17, 21]
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build publishToMavenLocal -x :examples:build 
    - name: Build Examples 
      run: ./gradlew build
    - name: Build Maven Template
      run: |
        cd grpc-jexpress-template
        mvn clean install
